library(dbnR)
library(data.table)
summary(SentimentDataCNN)
head(SentimentDataCNN)


SentimentDataCNN$Trump = as.double(SentimentDataCNN$Trump)
SentimentDataCNN$Biden = as.double(SentimentDataCNN$Biden)
SentimentDataCNN$Elections2020  = as.double(SentimentDataCNN$Elections2020)
SentimentDataCNN$KamalaHarris = as.double(SentimentDataCNN$KamalaHarris)
SentimentDataCNN$MAGA = as.double(SentimentDataCNN$MAGA)
SentimentDataCNN$COVID = as.double(SentimentDataCNN$COVID)
SentimentDataCNN$TrumpMeltdown = as.double(SentimentDataCNN$TrumpMeltdown)
SentimentDataCNN$Democrats = as.double(SentimentDataCNN$Democrats)
SentimentDataCNN$GOP = as.double(SentimentDataCNN$GOP)
SentimentDataCNN$Pennsylvania = as.double(SentimentDataCNN$Pennsylvania)
SentimentDataCNN$Obama = as.double(SentimentDataCNN$Obama)
SentimentDataCNN$Michigan = as.double(SentimentDataCNN$Michigan)
SentimentDataCNN$VoteHimOut = as.double(SentimentDataCNN$VoteHimOut)
SentimentDataCNN$CNN = as.double(SentimentDataCNN$CNN)
SentimentDataCNN$Republicans = as.double(SentimentDataCNN$Republicans)
SentimentDataCNN$Florida = as.double(SentimentDataCNN$Florida)
SentimentDataCNN$Georgia = as.double(SentimentDataCNN$Georgia)
SentimentDataCNN$China = as.double(SentimentDataCNN$China)
SentimentDataCNN$FoxNews = as.double(SentimentDataCNN$FoxNews)
SentimentDataCNN$Pence = as.double(SentimentDataCNN$Pence)
SentimentDataCNN$TrumpIsLosing = as.double(SentimentDataCNN$TrumpIsLosing)

size = 2
dt_train <- SentimentDataCNN
net <- dbnR::learn_dbn_struc(dt_train, size, method = "dmmhc")
f_dt_train <- fold_dt(dt_train, size)
fit <- dbnR::fit_dbn_params(net, f_dt_train, method = "mle-g")
dbnR::plot_dynamic_network(fit)
BIC(fit,f_dt_train)
AIC(fit,f_dt_train)
